ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DELETE FROM XLS.FORMATS   WHERE TABLE_SCHEMA = 'XLS' AND TABLE_NAME IN ('VIEW_COLUMNS', 'VIEW_FORMATS', 'VIEW_HANDLERS', 'VIEW_OBJECTS', 'VIEW_QUERIES', 'VIEW_TRANSLATIONS', 'VIEW_WORKBOOKS');
DELETE FROM XLS.HANDLERS  WHERE TABLE_SCHEMA = 'XLS' AND TABLE_NAME IN ('VIEW_COLUMNS', 'VIEW_FORMATS', 'VIEW_HANDLERS', 'VIEW_OBJECTS', 'VIEW_QUERIES', 'VIEW_TRANSLATIONS', 'VIEW_WORKBOOKS', 'SAVETODB_FRAMEWORK_EXTENSION');
DELETE FROM XLS.WORKBOOKS WHERE TABLE_SCHEMA = 'XLS' AND NAME IN ('savetodb_user_configuration.xlsx');

DROP PROCEDURE XLS.XL_UPDATE_TABLE_FORMAT;

DROP VIEW XLS.VIEW_COLUMNS;
DROP VIEW XLS.VIEW_FORMATS;
DROP VIEW XLS.VIEW_HANDLERS;
DROP VIEW XLS.VIEW_OBJECTS;
DROP VIEW XLS.VIEW_QUERIES;
DROP VIEW XLS.VIEW_TRANSLATIONS;
DROP VIEW XLS.VIEW_WORKBOOKS;

prompt SaveToDB Framework Extension removed
